---
title: "Complaints dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{css}
.value-box {
  height: 100px;
}

```


```{r setup, include=FALSE}
library(flexdashboard)
library(rio)
library ('plyr')
library(dplyr)
library(tidyverse)
library(plotly)
library(reactable)
library(htmltools)
library(ggplot2)
library(ggiraph)
```

```{r}
knitr::opts_chunk$set(fig.width=5, fig.height=3) 
```


```{r, include=FALSE}
#install.packages("RPostgreSQL")
#install.packages("RPostgres")
```

```{r, include=FALSE}

library(DBI)

# Obtaining the values of the environment variables

#db <- Sys.getenv("db_algorithm")  #database name
#db_host <- Sys.getenv("db_host") #localhost
#db_port <- Sys.getenv("db_port") #port
#db_user <- Sys.getenv("db_user") #credentials: user name
#db_pass <- Sys.getenv("db_pass") #credentials: user password


#Connecting to the Postgres database

#conn <- dbConnect(
#  RPostgres::Postgres(),
#  dbname = db,
#  host = db_host,
#  port = db_port,
#  user = db_user,
#  password = db_pass
#)

```


```{r, include=FALSE}
# import clean claims 21 table 
#clean_claims_21<- dbReadTable(conn, "clean_claims_21")

#keep the last version
#last_version <- max(clean_claims_21$version)

#clean_claims_21 <- clean_claims_21[ clean_claims_21$version == last_version, ]



```


```{r, include=FALSE}
#TEMPORAL: (delete after last commit)
setwd("C:/BID_Columbia/claims_assigment/outputs_temp")

clean_claims_21 <-import("stacking_encoded.dta")

##############
```


```{r, include=FALSE}
# import raw_claims_feb21 
#raw_claims_feb21 <- dbReadTable(conn, "raw_claims_feb21")
```


```{r, include=FALSE}
#TEMPORAL: (delete after last commit)
setwd("C:/BID_Columbia")

raw_claims_feb21 <-import("raw_claims_feb21.dta")

##############
```



Claims 2021
=====================================  

## Row
-----------------------------------------------------------------------

### Number of claims {.value-box}

```{r}
n_claims <- nrow(raw_claims_feb21)

valueBox(value = paste(format(n_claims, big.mark = ","), "", sep = " "), 
         caption = "Total Claims",
         icon = "fa-database",             #https://fontawesome.com/v4/icons/
         color = "#7636b3")
```


### Number of encoded claims {.value-box}

```{r}
n_encoded <- nrow(clean_claims_21)
percent_encoded <- paste( round(n_encoded/n_claims,2)*100, "%")

valueBox(value = paste(format(n_encoded, big.mark = ","), "/", percent_encoded  , sep = " "), 
         caption = "Encoded Claims",
         icon = "fa-arrow-circle-up",
         color = "#a249f5")
```



```{r, include=FALSE}

### Number of claims that are CGR responsability {.value-box}

n_cgr <- sum(raw_claims_feb21$competencia_cgr == 'S')

valueBox(value = paste(format(n_cgr, big.mark = ","), "", sep = " "),
         caption = "Claims that are CGR responsability", icon = "fa-tasks")

```


```{r, include=FALSE}

### Number of claims with simultaneous control {.value-box}

n_sc <- sum(raw_claims_feb21$a_control_simultaneo == 'S')

valueBox(value = paste(format(n_sc, big.mark = ","), "", sep = " "), 
         caption = "Claims with Simultaneous Control")#, 
         #color = active_color)
```


## Row
-----------------------------------------------------------------------


```{r}
# Recategorization for fur status
raw_claims_feb21 <- mutate(raw_claims_feb21, FUR_decision =
                                   case_when(estado_hec == "Calificado" | estado_hec == "Concluido" ~ "Yes",
                                             estado_hec == "Anulado" | estado_hec == "En Proceso" | estado_hec == "Pendiente" ~ "No" ) )

# Recategorization for fud status
raw_claims_feb21$FUD_decision<- ifelse(raw_claims_feb21$FUR_decision == "Yes" & raw_claims_feb21$numero_fud != "", "Yes", "No")


# Recategorization for PDE status
raw_claims_feb21$PDE_decision<- ifelse(raw_claims_feb21$numero_he != "" & (raw_claims_feb21$producto_aprobado == "Carpeta Atención de Denuncia" | raw_claims_feb21$producto_aprobado == "Desestimado") , "Yes", "No")


# Recategorization for CAD status
raw_claims_feb21$CAD_decision<- ifelse(raw_claims_feb21$numero_he != "" &  raw_claims_feb21$producto_aprobado == "Carpeta Atención de Denuncia" , "Yes", "No")
```


### FUR claims {.value-box}

```{r}
fur_claims <- sum(raw_claims_feb21$FUR_decision == "Yes")
percent_fur <-  paste( round(fur_claims/n_claims,2)*100, "%")

valueBox(value = paste(format(fur_claims, big.mark = ","), "/", percent_fur  , sep = " "),
         caption = "FUR Claims",
         icon = "fa-folder-open",            
         color = '#3fc1c9')
```

### FUD claims {.value-box}

```{r}
fud_claims <- sum(raw_claims_feb21$FUD_decision == "Yes")
percent_fud <-  paste( round(fud_claims/n_claims,2)*100, "%")

valueBox(value = paste(format(fud_claims, big.mark = ","), "/", percent_fud  , sep = " "),
         caption = "FUD Claims",
         icon = "fa-folder-open",             
         color = '#3fc1c9')
```


### PDE claims {.value-box}

```{r}
pde_claims <- sum(raw_claims_feb21$PDE_decision == "Yes")
percent_pde <-  paste( round(pde_claims/n_claims,2)*100, "%")

valueBox(value = paste(format(pde_claims, big.mark = ","), "/", percent_pde  , sep = " "),
         caption = "PDE Claims",
         icon = "fa-folder-open",             
         color = '#3fc1c9')
```


### CAD claims {.value-box}

```{r}
cad_claims <- sum(raw_claims_feb21$CAD_decision == "Yes")
percent_cad <-  paste( round(cad_claims/n_claims,2)*100, "%")

valueBox(value = paste(format(cad_claims, big.mark = ","), "/", percent_cad , sep = " "),
         caption = "CAD Claims",
         icon = "fa-folder-open",             
         color = '#3fc1c9')
```



## Row
-----------------------------------------------------------------------


### <b><font face="Arial" size="4px" color="#000000">FUR status</font></b>

```{r}

#Donut chart: fur status
fur_status_df <- as.data.frame(table(raw_claims_feb21$FUR_decision))

colnames(fur_status_df) <- c("fur_status", "n")
 
fig <- fur_status_df %>% plot_ly(labels = ~fur_status, values = ~n, marker = list(colors = c('#ff0000', '#00aa7f' )))
fig <- fig %>% add_pie(hole = 0.55, textfont = list(size = 13))
fig <- fig %>% layout(showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```

### <b><font face="Arial" size="4px" color="#000000">FUD status</font></b>

```{r}
#Donut chart: fud status
fud_status_df <- as.data.frame(table(raw_claims_feb21$FUD_decision))

colnames(fud_status_df) <- c("fud_status", "n")
 
fig <- fud_status_df %>% plot_ly(labels = ~fud_status, values = ~n, marker = list(colors = c('#ff0000', '#00aa7f')))
fig <- fig %>% add_pie(hole = 0.55, textfont = list(size = 13))
fig <- fig %>% layout(showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig

```


### <b><font face="Arial" size="4px" color="#000000">PDE status</font></b>

```{r}
#Donut chart: PDE status
pde_status_df <- as.data.frame(table(raw_claims_feb21$PDE_decision))

colnames(pde_status_df) <- c("pde_status", "n")
 
fig <- pde_status_df %>% plot_ly(labels = ~pde_status, values = ~n, marker = list(colors = c('#ff0000', '#00aa7f')))
fig <- fig %>% add_pie(hole = 0.55, textfont = list(size = 13))
fig <- fig %>% layout(showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig

```


### <b><font face="Arial" size="4px" color="#000000">CAD status</font></b>


```{r}
#Donut chart: PDE status
cad_status_df <- as.data.frame(table(raw_claims_feb21$CAD_decision))

colnames(cad_status_df) <- c("cad_status", "n")
 
fig <- cad_status_df %>% plot_ly(labels = ~cad_status, values = ~n, marker = list(colors = c('#ff0000', '#00aa7f')))
fig <- fig %>% add_pie(hole = 0.55, textfont = list(size = 13))
fig <- fig %>% layout(showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```



## Row
-----------------------------------------------------------------------


### <b><font face="Arial" size="4px" color="#000000">Encoded Claims: missings</font></b>

```{r, include=FALSE}

#table(clean_claims_21$aoc_willay)

#dataframe with two columns: variable and number of missings

df_missings <- ldply(clean_claims_21, function(var_value) sum(var_value ==""))
colnames(df_missings) <- c("variable", "n_missings")

#adding a new column: percentage of missings obs 
df_missings$percentage_missing = round( (df_missings$n_missings/ nrow(clean_claims_21))*100 , 1)
```


```{r, include=FALSE}

## FUNCTION FOR CUSTOMIZING NEXT TABLES
 
# Render a bar chart with a label on the left
bar_chart <- function(label, width = "100%", height = "14px", fill = "#00bfc4", background = NULL) {
  bar <- div(style = list(background = fill, width = width, height = height))
  chart <- div(style = list(flexGrow = 1, marginLeft = "6px", background = background), bar)
  div(style = list(display = "flex", alignItems = "center"), label, chart)
}
```


```{r}

tbl <- reactable(
  df_missings,
  pagination = TRUE,
  defaultSorted = "percentage_missing",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    variable = colDef(name = "Encoded variable"
 
    ),
    n_missings = colDef(
      name = "Number of missings",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(df_missings$n_missing), "%")
        # Add thousands separators
        value <- format(value, big.mark = ",")
        bar_chart(value, width = width, fill = "#39a7ad")
      },
      # And left-align the columns
      align = "left"
    ),
    percentage_missing = colDef(
      name = "% missings",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        # Format as percentages with 1 decimal place
        value <- paste0(format(value , nsmall = 1), "%")
        bar_chart(value, width = value, fill = "#ff0000", background = "#e1e1e1")
      },
      # And left-align the columns
      align = "left"
    )
  )
)

tbl

```


### <b><font face="Arial" size="4px" color="#000000">Encoded Claims: error rate per encoder</font></b>  


```{r, include=FALSE}
### Create a plot with error rate per encoder (Andrea/Edwar) (x axis is for number of batch, y for the error rate)

#keeping just claims reviewed by Jaime
tie_breaking_append <- clean_claims_21[ clean_claims_21$tiebraker_name == "Jaime", ]

#Andrea's number of errors
tie_breaking_append$error_andrea <- rep(0, nrow(tie_breaking_append))
tie_breaking_append$error_andrea[tie_breaking_append$chosen_encoder != "Andrea" & tie_breaking_append$chosen_encoder != "Andrea/Edwar"] <- 1

#Edwar's number of errors
tie_breaking_append$error_edwar <- rep(0, nrow(tie_breaking_append))
tie_breaking_append$error_edwar[tie_breaking_append$chosen_encoder != "Edwar" & tie_breaking_append$chosen_encoder != "Andrea/Edwar"] <- 1

#Number of observartions per batches
df2<- tie_breaking_append %>%
    group_by(date_batch) %>%
    summarise(obs = n()) 

#Number of errors per encoder and batch
df_andrea <- aggregate(tie_breaking_append$error_andrea, by=list(date_batch=tie_breaking_append$date_batch), FUN=sum)

colnames(df_andrea)[2] <- "error_andrea"

df_edwar <- aggregate(tie_breaking_append$error_edwar, by=list(date_batch=tie_breaking_append$date_batch), FUN=sum)

colnames(df_edwar)[2] <- "error_edwar"

#Error rate per encoder and batch
df_error_rate = merge(df2, df_andrea, by = "date_batch", all.x = TRUE)

df_error_rate = merge(df_error_rate, df_edwar, by = "date_batch", all.x = TRUE)


df_error_rate$error_rate_andrea <- round( (df_error_rate$error_andrea/df_error_rate$obs)*100 , 1)

df_error_rate$error_rate_edwar <- round( (df_error_rate$error_edwar/df_error_rate$obs)*100 , 1)


#Error rate per date batch and encoder
df_andrea_rate = df_error_rate[c('date_batch','error_rate_andrea')]

df_edwar_rate = df_error_rate[c('date_batch','error_rate_edwar')]


data_plot <- merge(df_andrea_rate, df_edwar_rate, by = "date_batch")
```


```{r}
#barplot: a plot with error rate per encoder (Andrea/Edwar)
fig <- plot_ly(data_plot, x = ~date_batch, y = ~error_rate_andrea, type = 'bar',  name = 'Andrea',
                marker = list(color = '#ccccc7') )
fig <- fig %>% add_trace(y = ~error_rate_edwar, name = 'Edwar',
                marker = list(color = '#00aa7f') )         

fig <- fig %>% 
        layout(title = "",
         xaxis = list(title = "Date batch",
                      zeroline = FALSE),
         yaxis = list(title = "Error rate (%)",
                      zeroline = FALSE))

fig
```

## Row
-----------------------------------------------------------------------

```{r, include=FALSE}

# creating a variable that identifies corruption claims
clean_claims_21$corruption_denunc<- ifelse(clean_claims_21$TIPO_DENUNCIA_PRIMARIO_14_CLASES=='LUCRO ILEGAL'| clean_claims_21$TIPO_DENUNCIA_PRIMARIO_14_CLASES=='USO INAPROPIADO DE RECURSOS NO FINANCIEROS'| clean_claims_21$TIPO_DENUNCIA_PRIMARIO_14_CLASES== 'FAVORITISMO' | clean_claims_21$TIPO_DENUNCIA_PRIMARIO_14_CLASES== 'COLUSION'| clean_claims_21$TIPO_DENUNCIA_PRIMARIO_14_CLASES== 'ABUSO DE AUTORIDAD O EXTORSION', 1, 0)

clean_claims_21$corruption_denunc<- ifelse(clean_claims_21$TIPO_DENUNCIA_PRIMARIO_14_CLASES=='', '', clean_claims_21$corruption_denunc)


# number and percentage of corruption claims 
corruption_claims_count <- subset(clean_claims_21, corruption_denunc!= "" ) %>% 
                         count(corruption_denunc, sort = TRUE)

corruption_claims_count$percentage <- round( (corruption_claims_count$n/sum(corruption_claims_count$n) )*100, 1)

corruption_claims_count <- corruption_claims_count %>%
  mutate(
    type = ifelse(corruption_claims_count$corruption_denunc == 1, "Yes", "No"),
    hover_text = paste0(type, ": ", n)
  ) %>%
  mutate(percentage_label = paste0(percentage,"%"))



```


### <b><font face="Arial" size="4px" color="#000000">Encoded Claims: corruption claims</font></b>  

```{r}
max = sum(corruption_claims_count$n)

gauge(corruption_claims_count$n[corruption_claims_count$corruption_denunc == 1], min = 0, max = max , gaugeSectors(
  success = c(round((2/3)*max) + 1 , max ), warning = c(round(max/3) + 1, round((2/3)*max) ), danger = c(0, round(max/3) ))
  , abbreviate = FALSE, abbreviateDecimals = 1)
```


### <b><font face="Arial" size="4px" color="#000000">Encoded Claims: corruption claims (%)</font></b>  


```{r}
gauge(corruption_claims_count$percentage[corruption_claims_count$corruption_denunc == 1], min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


```{r, include=FALSE}

donut_plot <- ggplot(corruption_claims_count, aes(y = n, fill = type)) +
  geom_bar_interactive(
    aes(x = 1, tooltip = hover_text),
    width = 0.1,
    stat = "identity",
    show.legend = FALSE
    ) +
  annotate(
    geom = "text",
    x = 0,
    y = 0,
    label = corruption_claims_count[["percentage_label"]][corruption_claims_count[["type"]] == "Yes"],
    size = 18,
    color = "magenta"
    ) +
  scale_fill_manual(values = c(No = "blue", Yes = "magenta")) +
  coord_polar(theta = "y") + theme(legend.position = c(0.8, 0.2)) +
  theme_void()

ggiraph(ggobj = donut_plot )
```

## Row
-----------------------------------------------------------------------


### <b><font face="Arial" size="4px" color="#000000">Encoded Claims: corruption claims by deparment - statistics</font></b>  


```{r, include=FALSE}
corruption_dep <- subset(mutate_each(clean_claims_21, funs(toupper)), DEPARTAMENTO!= "" )

#delete special characters from DEPARTAMENTO
corruption_dep$DEPARTAMENTO <- iconv(corruption_dep$DEPARTAMENTO, from="UTF-8",to="ASCII//TRANSLIT")

#Solving some issues with DEPARTAMENTO (temporal) / this is not necessarily correct 
corruption_dep$DEPARTAMENTO <- gsub('AREQUIPA, LIMA', 'AREQUIPA', corruption_dep$DEPARTAMENTO)
corruption_dep$DEPARTAMENTO <- gsub('LIMA, AYACUCHO', 'LIMA', corruption_dep$DEPARTAMENTO)
corruption_dep$DEPARTAMENTO <- gsub('MINISTERIO DE DEFENSA', 'LIMA', corruption_dep$DEPARTAMENTO)
corruption_dep$DEPARTAMENTO <- gsub('PIURA, LIMA', 'LIMA', corruption_dep$DEPARTAMENTO)
corruption_dep$DEPARTAMENTO <- gsub('TUMBES, PIURA, LAMBAYEQUE, CALLAO, TACNA, AREQUIPA', 'TUMBES', corruption_dep$DEPARTAMENTO)
corruption_dep$DEPARTAMENTO <- gsub('MONQUEGUA', 'MOQUEGUA', corruption_dep$DEPARTAMENTO)


corruption_dep <- corruption_dep %>%
  group_by(DEPARTAMENTO) %>%
  summarise(
    n = n()
  )

corruption_dep$percentage <- round( (corruption_dep$n/sum(corruption_dep$n) )*100, 1)
```


```{r}

tbl <- reactable(
  corruption_dep,
  pagination = TRUE,
  defaultSorted = "n",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    DEPARTAMENTO = colDef(name = "Department"
 
    ),
    n = colDef(
      name = "Number of claims",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(corruption_dep$n), "%")
        # Add thousands separators
        value <- format(value, big.mark = ",")
        bar_chart(value, width = width, fill = "#3fc1c9")
      },
      # And left-align the columns
      align = "left"
    ),
    percentage = colDef(
      name = "Percentage",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        # Format as percentages with 1 decimal place
        value <- paste0(format(value , nsmall = 1), "%")
        bar_chart(value, width = value, fill = "#fc5185", background = "#e1e1e1")
      },
      # And left-align the columns
      align = "left"
    )
  )
)

tbl
```



### <b><font face="Arial" size="4px" color="#000000">Encoded Claims: corruption claims by deparment - map</font></b>  


```{r, include=FALSE}
library(rgdal)
library(broom)
library(rgeos)
library(maptools)
library(ggplot2)
library(viridis)
library(scales)

#Map file location (TEMPORAL)
dirmapas <- "C:/BID_Columbia/claims_dashboard/maps/DEPARTAMENTO" 
setwd(dirmapas)

# The black and white polygon map
departamentos<-readOGR(dsn="DEPARTAMENTO_27_04_2015.shp", layer="DEPARTAMENTO_27_04_2015")

#summary(departamentos)

departamentos$NOMBDEP

#head(departamentos@data)

#plot(departamentos)

#We must transform the data to be able to make a graph with ggplot
departamentos_fortified <- tidy(departamentos, region =  "NOMBDEP")
#unique(departamentos_fortified$id)


#We leave only the id and n columns
corruption_dep$id <- corruption_dep$DEPARTAMENTO
corruption_dep <- corruption_dep[,c("id","n")]

#left join
departamentos_fortified_ <-merge(x = departamentos_fortified, y = corruption_dep, by = c("id"), all.x = TRUE)


```


```{r}
#map plot
dep_plot <- ggplot() +
        geom_polygon(data = departamentos_fortified_, aes(fill = n, x = long, y = lat, group = group), colour= "gray", size=0.05, alpha=0.9) +
        theme_void() +
        scale_fill_viridis(option = 'D', trans = "log2",  breaks = trans_breaks("log2", function(x) 2^x), name="Claims") +
        theme(  
                text = element_text(size= 7, color = "#22211d"),
                
                plot.title = element_text(size= 14, hjust=0.01, color = "black", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
                plot.subtitle = element_text(size= 12, hjust=0.01, color = "#4e4d47", margin = margin(b = -0.1, t = 0.43, l = 2, unit = "cm")),
                plot.caption = element_text( size=10, color = "black", margin = margin(b = 0.3, r=-99, unit = "cm") ),
        ) +
        coord_map()

dep_plot
```


## Row
-----------------------------------------------------------------------

```{r, include=FALSE}
## MERGE RAW_CLAIMS_FEB21 & CLEAN_CLAIMS_21

#convert all vars to string
clean_claims_21_ch <- clean_claims_21 %>%
  mutate(across(everything(), as.character))

raw_claims_feb21_ch <- raw_claims_feb21 %>%
  mutate(across(everything(), as.character))

#deleting white spaces
clean_claims_21_ch$expediente <- gsub(" ", "", clean_claims_21_ch$expediente) 
clean_claims_21_ch$fur <- gsub(" ", "", clean_claims_21_ch$fur) 
clean_claims_21_ch$numero_hec <- gsub(" ", "", clean_claims_21_ch$numero_hec) 
clean_claims_21_ch$numero_hecho <- gsub(" ", "", clean_claims_21_ch$numero_hecho) 
clean_claims_21_ch$numero_fud  <- gsub(" ", "", clean_claims_21_ch$numero_fud ) 

raw_claims_feb21_ch$expediente <- gsub(" ", "", raw_claims_feb21_ch$expediente) 
raw_claims_feb21_ch$fur <- gsub(" ", "", raw_claims_feb21_ch$fur) 
raw_claims_feb21_ch$numero_hec <- gsub(" ", "", raw_claims_feb21_ch$numero_hec) 
raw_claims_feb21_ch$numero_hecho <- gsub(" ", "", raw_claims_feb21_ch$numero_hecho) 
raw_claims_feb21_ch$numero_fud  <- gsub(" ", "", raw_claims_feb21_ch$numero_fud ) 

#from lowercase to uppercase
clean_claims_21_ch <- mutate_each(clean_claims_21_ch, funs(toupper))
raw_claims_feb21_ch <- mutate_each(raw_claims_feb21_ch, funs(toupper))

#solving issues with numero fud var
clean_claims_21_ch$numero_fud <- gsub('NAN', '', clean_claims_21_ch$numero_fud)

#creating variable that will help us with the merge
clean_claims_21_ch$clean_claims_21 <- "1"
raw_claims_feb21_ch$raw_claims_feb21 <- "1"

#solving issues with expediente var (deleting leading zeros)

clean_claims_21_ch$expediente <- sub("^0+", "", clean_claims_21_ch$expediente) 
raw_claims_feb21_ch$expediente <- sub("^0+", "", raw_claims_feb21_ch$expediente) 

#Merge claims 21 with codified claims (todo: solve issues)

claims_21 <- merge(x = raw_claims_feb21_ch, y = clean_claims_21_ch, by = c("expediente", "fur", "numero_hec", "numero_hecho", "numero_fud"), all.x = TRUE)

```


```{r, include=FALSE}
#extra claims
nrow(claims_21) - nrow(raw_claims_feb21)

#claims that were not matched
nrow(clean_claims_21) - table(claims_21$clean_claims_21)
```


### <b><font face="Arial" size="4px" color="#000000">Claims by entity</font></b>  


```{r, include=FALSE}

#delete special characters from TIPO_DE_ENTIDAD
claims_21$TIPO_DE_ENTIDAD <- iconv(claims_21$TIPO_DE_ENTIDAD, from="UTF-8",to="ASCII//TRANSLIT")

#Solving some issues with TIPO_DE_ENTIDAD 
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE LA PRODUCCION', 'DIRECCION REGIONAL DE PRODUCCION', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE SALUD DE AREQUIPA', 'DIRECCION REGIONAL DE SALUD AREQUIPA', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE SALUD DE CALLAO', 'DIRECCION REGIONAL DE SALUD CALLAO', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE SALUD DE UCAYALI', 'DIRECCION REGIONAL DE SALUD UCAYALI', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE SALUD DE LA LIBERTAD', 'DIRECCION REGIONAL DE SALUD LA LIBERTAD', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE SALUD DE SAN MARTIN', 'DIRECCION REGIONAL DE SALUD SAN MARTIN', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE TRABAJO Y PROMOCION DE EMPLEO', 'DIRECCION REGIONAL DE TRABAJO Y PROMOCION DEL EMPLEO', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE TRABAJO Y PROMOCION DE EMPLEO', 'DIRECCION REGIONAL DE TRABAJO Y PROMOCION DEL EMPLEO', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE TRANSPORTES', 'DIRECCION REGIONAL DE TRANSPORTE Y COMUNICACIONES', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE TRANSPORTES Y COMUNICACIONES', 'DIRECCION REGIONAL DE TRANSPORTE Y COMUNICACIONES', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('DIRECCION REGIONAL DE TRANSPORTES Y COMUNICACIONES', 'DIRECCION REGIONAL DE TRANSPORTE Y COMUNICACIONES', claims_21$TIPO_DE_ENTIDAD)
claims_21$TIPO_DE_ENTIDAD <- gsub('MINISTERIO DE PRODUCCION', 'MINISTERIO DE LA PRODUCCION', claims_21$TIPO_DE_ENTIDAD)

```


```{r}
# number and percentage of denuncias per type of entity

type_entity_count <- subset(claims_21, TIPO_DE_ENTIDAD!= "" ) %>%
  group_by(TIPO_DE_ENTIDAD) %>%
  summarise(
    n = n(),
    percentage = NaN,
    n_fur = sum(FUR_decision == "YES"),
    n_fud = sum(FUD_decision == "YES"),
    n_pde = sum(PDE_decision == "YES"),
    n_cad = sum(CAD_decision == "YES"),
  )

type_entity_count$percentage <- round( (type_entity_count$n/sum(type_entity_count$n) )*100, 1)


tbl <- reactable(
  type_entity_count,
  pagination = TRUE,
  defaultSorted = "n",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    TIPO_DE_ENTIDAD = colDef(name = "Entity type", width = 200),
    n = colDef(
      name = "Number of claims",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(type_entity_count$n), "%")
        # Add thousands separators
        value <- format(value, big.mark = ",")
        bar_chart(value, width = width, fill = "#3fc1c9")
      },
      # And left-align the columns
      align = "left"
    ),
    percentage = colDef(
      name = "Percentage",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        # Format as percentages with 1 decimal place
        value <- paste0(format(value , nsmall = 1), "%")
        bar_chart(value, width = value, fill = "#fc5185", background = "#e1e1e1")
      },
      # And left-align the columns
      align = "left"
    ),
    n_fur = colDef(name = "FUR", width = 55),
    n_fud = colDef(name = "FUD", width = 55),
    n_pde = colDef(name = "PDE", width = 55),
    n_cad = colDef(name = "CAD", width = 55)
  )
)

tbl
```


### <b><font face="Arial" size="4px" color="#000000">Claims per type of primary class</font></b>  


```{r}

#delete special characters from TIPO_DENUNCIA_PRIMARIO_14_CLASES
clean_claims_21_ch$TIPO_DENUNCIA_PRIMARIO_14_CLASES <- iconv(clean_claims_21_ch$TIPO_DENUNCIA_PRIMARIO_14_CLASES, from="UTF-8",to="ASCII//TRANSLIT")


#Solving some issues with TIPO_DENUNCIA_PRIMARIO_14_CLASES
clean_claims_21_ch$TIPO_DENUNCIA_PRIMARIO_14_CLASES <- gsub('USO INAPROPIADO DE LOS RECURSOS NO FINANCIEROS', 'USO INAPROPIADO DE RECURSOS NO FINANCIEROS', clean_claims_21_ch$TIPO_DENUNCIA_PRIMARIO_14_CLASES)

clean_claims_21_ch$TIPO_DENUNCIA_PRIMARIO_14_CLASES <- gsub('USO INAPROPIADO DE RECURSOS NO FINACIEROS', 'USO INAPROPIADO DE RECURSOS NO FINANCIEROS', clean_claims_21_ch$TIPO_DENUNCIA_PRIMARIO_14_CLASES)


# number and percentage of denuncias per type of primary class
primary_class_count <- subset(clean_claims_21_ch, TIPO_DENUNCIA_PRIMARIO_14_CLASES!= "" ) %>% 
                         count(TIPO_DENUNCIA_PRIMARIO_14_CLASES, sort = TRUE) 

primary_class_count$percentage <- round( (primary_class_count$n/sum(primary_class_count$n) )*100, 1)


tbl <- reactable(
  primary_class_count,
  pagination = TRUE,
  defaultSorted = "n",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    TIPO_DENUNCIA_PRIMARIO_14_CLASES = colDef(name = "Type of primary class"
 
    ),
    n = colDef(
      name = "Number of obs",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(primary_class_count$n), "%")
        # Add thousands separators
        value <- format(value, big.mark = ",")
        bar_chart(value, width = width, fill = "#3fc1c9")
      },
      # And left-align the columns
      align = "left"
    ),
    percentage = colDef(
      name = "Percentage",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        # Format as percentages with 1 decimal place
        value <- paste0(format(value , nsmall = 1), "%")
        bar_chart(value, width = value, fill = "#fc5185", background = "#e1e1e1")
      },
      # And left-align the columns
      align = "left"
    )
  )
)

tbl
```


```{r, include=FALSE}

#delete special characters from DEPARTAMENTO
clean_claims_21$DEPARTAMENTO <- iconv(clean_claims_21$DEPARTAMENTO, from="UTF-8",to="ASCII//TRANSLIT")

#todo: create an interactive map (ask Marco)

#number of corruption claims by dep 
corruption_claims_dep <- subset(clean_claims_21[c("DEPARTAMENTO", "corruption_denunc")] , DEPARTAMENTO!= ""  ) 

corruption_claims_dep$corruption_denunc <- as.numeric(corruption_claims_dep$corruption_denunc)

corruption_claims_dep %>% 
   group_by(DEPARTAMENTO) %>% summarise_each(funs(sum)) 

```


## Row
-----------------------------------------------------------------------


### <b><font face="Arial" size="4px" color="#000000">Claims by office</font></b>  


```{r}

uo_ara_count <- subset(raw_claims_feb21, uo_ara!= "" ) %>%
  group_by(uo_ara) %>%
  summarise(
    n = n(),
    percentage = NaN,
    n_fur = sum(FUR_decision == "Yes"),
    n_fud = sum(FUD_decision == "Yes"),
    n_pde = sum(PDE_decision == "Yes"),
    n_cad = sum(CAD_decision == "Yes"),
  )

uo_ara_count$percentage <- round( (uo_ara_count$n/sum(uo_ara_count$n) )*100, 1)


tbl <- reactable(
  uo_ara_count,
  pagination = TRUE,
  defaultSorted = "n",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    uo_ara = colDef(name = "Office name", width = 200),
    n = colDef(
      name = "Number of claims",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(uo_ara_count$n), "%")
        # Add thousands separators
        value <- format(value, big.mark = ",")
        bar_chart(value, width = width, fill = "#3fc1c9")
      },
      # And left-align the columns
      align = "left"
    ),
    percentage = colDef(
      name = "Percentage",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        # Format as percentages with 1 decimal place
        value <- paste0(format(value , nsmall = 1), "%")
        bar_chart(value, width = value, fill = "#fc5185", background = "#e1e1e1")
      },
      # And left-align the columns
      align = "left"
    ),
    n_fur = colDef(name = "FUR", width = 55),
    n_fud = colDef(name = "FUD", width = 55),
    n_pde = colDef(name = "PDE", width = 55),
    n_cad = colDef(name = "CAD", width = 55)
  )
)

tbl
```


### <b><font face="Arial" size="4px" color="#000000">Claims by analyst</font></b>  


```{r}

ara_count <- subset(raw_claims_feb21, ara!= ", " ) %>%
  group_by(ara) %>%
  summarise(
    n = n(),
    percentage = NaN,
    n_fur = sum(FUR_decision == "Yes"),
    n_fud = sum(FUD_decision == "Yes"),
    n_pde = sum(PDE_decision == "Yes"),
    n_cad = sum(CAD_decision == "Yes"),
  )

ara_count$percentage <- round( (ara_count$n/sum(ara_count$n) )*100, 1)


tbl <- reactable(
  ara_count,
  pagination = TRUE,
  defaultSorted = "n",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    ara = colDef(name = "Analyst name", width = 200),
    n = colDef(
      name = "Number of claims",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(ara_count$n), "%")
        # Add thousands separators
        value <- format(value, big.mark = ",")
        bar_chart(value, width = width, fill = "#3fc1c9")
      },
      # And left-align the columns
      align = "left"
    ),
    percentage = colDef(
      name = "Percentage",
      defaultSortOrder = "desc",
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        # Format as percentages with 1 decimal place
        value <- paste0(format(value , nsmall = 1), "%")
        bar_chart(value, width = value, fill = "#fc5185", background = "#e1e1e1")
      },
      # And left-align the columns
      align = "left"
    ),
    n_fur = colDef(name = "FUR", width = 55),
    n_fud = colDef(name = "FUD", width = 55),
    n_pde = colDef(name = "PDE", width = 55),
    n_cad = colDef(name = "CAD", width = 55)
  )
)

tbl
```




Page 2
=====================================  










