---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rio)
library(dplyr)
```


```{r setup, include=FALSE}
#install.packages("RPostgreSQL")
#install.packages("RPostgres")
```

```{r setup, include=FALSE}

#library(DBI)

# Obtaining the values of the environment variables

#db <- Sys.getenv("db_algorithm")  #database name
#db_host <- Sys.getenv("db_host") #localhost
#db_port <- Sys.getenv("db_port") #port
#db_user <- Sys.getenv("db_user") #credentials: user name
#db_pass <- Sys.getenv("db_pass") #credentials: user password


#Connecting to the Postgres database

#conn <- dbConnect(
#  RPostgres::Postgres(),
#  dbname = db,
#  host = db_host,
#  port = db_port,
#  user = db_user,
#  password = db_pass
#)

```


```{r setup, include=FALSE}
# import clean claims 21 table 
#raw_historical_claims=dbReadTable(conn, "clean_claims_21")

```


```{r setup, include=FALSE}

### Create a plot with error rate per encoder (Andrea/Edwar) (x axis is for number of batch, y for the error rate)

# set working directory
setwd("C:/BID_Columbia/claims_assigment/outputs_temp")


tie_breaking_append <- import('stacking_encoded.dta')

#keeping just claims reviewed by Jaime
tie_breaking_append <- tie_breaking_append[ tie_breaking_append$tiebraker_name == "Jaime", ]

#Andrea's number of errors
tie_breaking_append$error_andrea <- rep(0, nrow(tie_breaking_append))
tie_breaking_append$error_andrea[tie_breaking_append$chosen_encoder != "Andrea" & tie_breaking_append$chosen_encoder != "Andrea/Edwar"] <- 1

#Edwar's number of errors
tie_breaking_append$error_edwar <- rep(0, nrow(tie_breaking_append))
tie_breaking_append$error_edwar[tie_breaking_append$chosen_encoder != "Edwar" & tie_breaking_append$chosen_encoder != "Andrea/Edwar"] <- 1

#Number of observartions per batches
df2<- tie_breaking_append %>%
    group_by(date_batch) %>%
    summarise(obs = n()) 

#Number of errors per encoder and batch
df_andrea <- aggregate(tie_breaking_append$error_andrea, by=list(date_batch=tie_breaking_append$date_batch), FUN=sum)

colnames(df_andrea)[2] <- "error_andrea"

df_edwar <- aggregate(tie_breaking_append$error_edwar, by=list(date_batch=tie_breaking_append$date_batch), FUN=sum)

colnames(df_edwar)[2] <- "error_edwar"

#Error rate per encoder and batch
df_error_rate = merge(df2, df_andrea, by = "date_batch", all.x = TRUE)

df_error_rate = merge(df_error_rate, df_edwar, by = "date_batch", all.x = TRUE)


df_error_rate$error_rate_andrea <- (df_error_rate$error_andrea/df_error_rate$obs)*100

df_error_rate$error_rate_edwar <- (df_error_rate$error_edwar/df_error_rate$obs)*100


#Error rate per date batch and encoder
df_andrea_rate = df_error_rate[c('date_batch','error_rate_andrea')]
colnames(df_andrea_rate)[2]<- c("error_rate")

df_andrea_rate$encoder <- 'Andrea'


df_edwar_rate = df_error_rate[c('date_batch','error_rate_edwar')]
colnames(df_edwar_rate)[2]<- c("error_rate")

df_edwar_rate$encoder <- 'Edwar'


data_plot <- rbind(df_andrea_rate, df_edwar_rate)
        
```






